
[package]
name = "win32_window"
version = "0.1.0"
authors = ["Stern Gerlach <drksugi@gmail.com>"]
edition = "2018"

[dependencies]

[target."cfg(windows)".dependencies]
winapi={ version="0.3.6", features = ["winuser", "libloaderapi"] }
